<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wedding Invitation Catalog</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        .filter-btn {
            transition: all 0.3s ease;
        }
        .filter-btn:hover {
            transform: translateY(-2px);
        }
        .filter-btn.active {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        .product-card {
            transition: all 0.3s ease;
        }
        .product-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 25px rgba(0,0,0,0.1);
        }
        .image-container {
            position: relative;
            overflow: hidden;
        }
        .image-container img {
            transition: transform 0.3s ease;
        }
        .image-container:hover img {
            transform: scale(1.05);
        }
        .badge-fast {
            background: linear-gradient(45deg, #00c851, #00ff00);
            color: white;
            font-size: 0.7rem;
            padding: 2px 8px;
            border-radius: 12px;
            position: absolute;
            top: 8px;
            right: 8px;
            z-index: 10;
        }
    </style>
</head>
<body class="bg-gray-50">
    <!-- Header -->
    <header class="bg-white shadow-sm sticky top-0 z-50">
        <div class="container mx-auto px-4 py-4">
            <div class="flex items-center justify-between">
                <div class="flex items-center space-x-4">
                    <div class="w-10 h-10 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full flex items-center justify-center">
                        <span class="text-white font-bold">W</span>
                    </div>
                    <h1 class="text-2xl font-bold text-gray-800">Wedding Invitation</h1>
                </div>
                <div class="flex items-center space-x-4">
                    <div class="relative">
                        <input type="text" id="searchInput" placeholder="Cari tema..." 
                               class="pl-10 pr-4 py-2 border border-gray-300 rounded-full focus:outline-none focus:ring-2 focus:ring-purple-500">
                        <svg class="absolute left-3 top-2.5 w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                        </svg>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Filter Section -->
    <section class="bg-white py-6 shadow-sm">
        <div class="container mx-auto px-4">
            <div class="flex flex-wrap justify-center gap-3" id="filterContainer">
                <!-- Filter buttons will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Main Content -->
    <main class="container mx-auto px-4 py-8">
        <div class="mb-6 text-center">
            <p class="text-gray-600">
                Menampilkan <span id="productCount">0</span> dari <span id="totalProducts">0</span> tema
            </p>
        </div>

        <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-6" id="productGrid">
            <!-- Products will be generated by JavaScript -->
        </div>

        <div id="noResults" class="hidden text-center py-12">
            <p class="text-gray-500 text-lg">Tidak ada tema yang ditemukan untuk pencarian ini.</p>
        </div>
    </main>

    <!-- Footer -->
    <footer class="bg-gray-800 text-white py-8 mt-12">
        <div class="container mx-auto px-4 text-center">
            <p>&copy; 2024 Wedding Invitation Catalog. All rights reserved.</p>
        </div>
    </footer>

    <script>
        // Product data
        const products = [
            { id: 1, nama: "Sunda 1", kategori: "Adat", linkPreview: "https://app.smstory.id/pilihan-tema/sunda-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/Rkjn0dzm/01-Sunda-01.png", keterangan: "" },
            { id: 2, nama: "Jawa 1", kategori: "Adat", linkPreview: "https://app.smstory.id/pilihan-tema/jawa-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/hR9CbpDv/02-Jawa-01.png", keterangan: "" },
            { id: 3, nama: "Minang 1", kategori: "Adat", linkPreview: "https://app.smstory.id/pilihan-tema/minang-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/m5j4cHNw/03-Minang-01.png", keterangan: "" },
            { id: 4, nama: "Psh-01", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/psh-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/5XRf9vBY/04-PSH-01.png", keterangan: "" },
            { id: 5, nama: "Psh-02", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/psh-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/3Y0jpsCD/05-PSH-02.png", keterangan: "" },
            { id: 6, nama: "Psh-03", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/psh-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/h116tDrh/06-PSH-03.png", keterangan: "" },
            { id: 7, nama: "Psh-04", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/psh-04?sr=iiwedding", linkGambar: "https://i.ibb.co.com/cKt19Xp2/07-PSH-04.png", keterangan: "" },
            { id: 8, nama: "Psh-05", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/psh-05?sr=iiwedding", linkGambar: "https://i.ibb.co.com/k2rQstdR/08-PSH-05.png", keterangan: "" },
            { id: 9, nama: "Psh-06", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/psh-06?sr=iiwedding", linkGambar: "https://i.ibb.co.com/pBhwF7mm/09-PSH-06.png", keterangan: "" },
            { id: 10, nama: "Mss-01", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/mss-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/bMMcrbQB/10-MSS-01.png", keterangan: "" },
            { id: 11, nama: "Mss-02", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/mss-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/QjJfc6YT/11-MSS-02.png", keterangan: "" },
            { id: 12, nama: "Mss-03", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/mss-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/FbgYwBvF/12-MSS-03.png", keterangan: "" },
            { id: 13, nama: "Mss-04", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/mss-04?sr=iiwedding", linkGambar: "https://i.ibb.co.com/C56W3S35/13-MSS-04.png", keterangan: "" },
            { id: 14, nama: "Mss-05", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/mss-05?sr=iiwedding", linkGambar: "https://i.ibb.co.com/GvbzYZgH/14-MSS-05.png", keterangan: "" },
            { id: 15, nama: "Mss-06", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/mss-06?sr=iiwedding", linkGambar: "https://i.ibb.co.com/84xGkZWj/15-MSS-06.png", keterangan: "" },
            { id: 16, nama: "Nursa-01", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/nursa-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/8DyrSdCL/16-Nursa-01.png", keterangan: "" },
            { id: 17, nama: "Nursa-02", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/nursa-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/qPj7k5y/17-Nursa-02.png", keterangan: "" },
            { id: 18, nama: "Nursa-03", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/nursa-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/fRsRDzD/18-Nursa-03.png", keterangan: "" },
            { id: 19, nama: "Nursa-04", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/nursa-04?sr=iiwedding", linkGambar: "https://i.ibb.co.com/vCQmZqRN/19-Nursa-04.png", keterangan: "" },
            { id: 20, nama: "Nursa-05", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/nursa-05?sr=iiwedding", linkGambar: "https://i.ibb.co.com/rK7n8VKy/20-Nursa-05.png", keterangan: "" },
            { id: 21, nama: "Nursa-06", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/nursa-06?sr=iiwedding", linkGambar: "https://i.ibb.co.com/G35B0SC9/21-Nursa-06.png", keterangan: "" },
            { id: 22, nama: "Love-Cartoon-01", kategori: "Islami", linkPreview: "https://app.smstory.id/pilihan-tema/love-cartoon-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/G48JPDpz/22-LOVE-CARTOON-01.png", keterangan: "" },
            { id: 23, nama: "Love-Cartoon-02", kategori: "Islami", linkPreview: "https://app.smstory.id/pilihan-tema/love-cartoon-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/gMhFfnJR/23-LOVE-CARTOON-02.png", keterangan: "" },
            { id: 24, nama: "Love-Cartoon-03", kategori: "Islami", linkPreview: "https://app.smstory.id/pilihan-tema/love-cartoon-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/WNtP6vmJ/24-LOVE-CARTOON-03.png", keterangan: "" },
            { id: 25, nama: "Butterfly-Fx-01", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/butterfly-fx-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/Vc8F6Spy/25-Butterfly-FX-01.png", keterangan: "" },
            { id: 26, nama: "Butterfly-Fx-02", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/butterfly-fx-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/x8LCydnK/26-Butterfly-FX-02.png", keterangan: "" },
            { id: 27, nama: "Butterfly-Fx-03", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/butterfly-fx-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/K8bwBQ7/27-Butterfly-FX-03.png", keterangan: "" },
            { id: 28, nama: "Swn-01", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/swn-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/WNjybWKS/28-SWN-01.png", keterangan: "" },
            { id: 29, nama: "Swn-02", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/swn-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/2mgTnQy/29-SWN-02.png", keterangan: "" },
            { id: 30, nama: "Swn-03", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/swn-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/C5GcrjDj/30-SWN-03.png", keterangan: "" },
            { id: 31, nama: "Swn-04", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/swn-04?sr=iiwedding", linkGambar: "https://i.ibb.co.com/mFFBGxQH/31-SWN-04.png", keterangan: "" },
            { id: 32, nama: "Swn-05", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/swn-05?sr=iiwedding", linkGambar: "https://i.ibb.co.com/TxZd7kwD/32-SWN-05.png", keterangan: "" },
            { id: 33, nama: "Swn-06", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/swn-06?sr=iiwedding", linkGambar: "https://i.ibb.co.com/prWpcvS9/33-SWN-06.png", keterangan: "" },
            { id: 34, nama: "Swn-07", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/swn-07?sr=iiwedding", linkGambar: "https://i.ibb.co.com/4Zw1KHhX/34-SWN-07.png", keterangan: "" },
            { id: 35, nama: "Swn-08", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/swn-08?sr=iiwedding", linkGambar: "https://i.ibb.co.com/WNB6Xwtr/35-SWN-08.png", keterangan: "" },
            { id: 36, nama: "Swn-09", kategori: "Elegant", linkPreview: "https://app.smstory.id/pilihan-tema/swn-09?sr=iiwedding", linkGambar: "https://i.ibb.co.com/99BxCF6q/36-SWN-09.png", keterangan: "" },
            { id: 37, nama: "Wavy-Sfe-01", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/wavy-sfe-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/v4g3JRQS/37-Wavy-SFE-01.jpg", keterangan: "" },
            { id: 38, nama: "Wavy-Sfe-02", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/wavy-sfe-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/cckMnfJ1/38-Wavy-SFE-02.jpg", keterangan: "" },
            { id: 39, nama: "Wavy-Sfe-03", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/wavy-sfe-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/LXQmRSyL/39-Wavy-SFE-03.jpg", keterangan: "" },
            { id: 40, nama: "Wavy-Sfe-04", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/wavy-sfe-04?sr=iiwedding", linkGambar: "https://i.ibb.co.com/Ngs3rSDB/40-Wavy-SFE-04.jpg", keterangan: "" },
            { id: 41, nama: "Wavy-Sfe-05", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/wavy-sfe-05?sr=iiwedding", linkGambar: "https://i.ibb.co.com/fVGdtpGg/41-Wavy-SFE-05.jpg", keterangan: "" },
            { id: 42, nama: "Wavy-Sfe-06", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/wavy-sfe-06?sr=iiwedding", linkGambar: "https://i.ibb.co.com/1YWVrD1w/42-Wavy-SFE-06.jpg", keterangan: "" },
            { id: 43, nama: "Wavy-Sfe-07", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/wavy-sfe-07?sr=iiwedding", linkGambar: "https://i.ibb.co.com/qMBVdLzk/43-Wavy-SFE-07.jpg", keterangan: "" },
            { id: 44, nama: "Wavy-Sfe-08", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/wavy-sfe-08?sr=iiwedding", linkGambar: "https://i.ibb.co.com/LhzSNLQG/44-Wavy-SFE-08.jpg", keterangan: "" },
            { id: 45, nama: "Wavy-Sfe-09", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/wavy-sfe-09?sr=iiwedding", linkGambar: "https://i.ibb.co.com/HfhHYFTj/45-Wavy-SFE-09.jpg", keterangan: "" },
            { id: 46, nama: "Aqiqah-Givemeart-Mks-01", kategori: "Aqiqah", linkPreview: "https://app.smstory.id/pilihan-tema/aqiqah-givemeart-mks-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/x8fqPbyY/46-Aqiqah-Givemeart-Mks-01.png", keterangan: "" },
            { id: 47, nama: "Aqiqah-Givemeart-Mks-02", kategori: "Aqiqah", linkPreview: "https://app.smstory.id/pilihan-tema/aqiqah-givemeart-mks-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/7ddDmpSM/47-Aqiqah-Givemeart-Mks-02.png", keterangan: "" },
            { id: 48, nama: "Aqiqah-Givemeart-Mks-03", kategori: "Aqiqah", linkPreview: "https://app.smstory.id/pilihan-tema/aqiqah-givemeart-mks-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/k24BSrFb/48-Aqiqah-Givemeart-Mks-03.png", keterangan: "" },
            { id: 49, nama: "Ethnic-Sm-01", kategori: "Batik", linkPreview: "https://app.smstory.id/pilihan-tema/ethnic-sm-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/B5MvMMRV/49-Ethnic-SM-01.jpg", keterangan: "" },
            { id: 50, nama: "Ethnic-Sm-02", kategori: "Batik", linkPreview: "https://app.smstory.id/pilihan-tema/ethnic-sm-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/99ZWzZYb/50-Ethnic-SM-02.jpg", keterangan: "" },
            { id: 51, nama: "Ethnic-Sm-03", kategori: "Batik", linkPreview: "https://app.smstory.id/pilihan-tema/ethnic-sm-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/Z6QpLn2F/51-Ethnic-SM-03.jpg", keterangan: "" },
            { id: 52, nama: "Autoplay-Floral-Dance-01", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/autoplay-floral-dance-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/KpBGLwwT/52-Autoplay-Floral-Dance-01.png", keterangan: "" },
            { id: 53, nama: "Autoplay-Floral-Dance-02", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/autoplay-floral-dance-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/PffKr5C/53-Autoplay-Floral-Dance-02.png", keterangan: "" },
            { id: 54, nama: "Autoplay-Floral-Dance-03", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/autoplay-floral-dance-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/TfXFZh0/54-Autoplay-Floral-Dance-03.png", keterangan: "" },
            { id: 55, nama: "Autoplay-Floral-Dance-04", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/autoplay-floral-dance-04?sr=iiwedding", linkGambar: "https://i.ibb.co.com/TM8stBsV/55-Autoplay-Floral-Dance-04.png", keterangan: "" },
            { id: 56, nama: "Autoplay-Floral-Dance-05", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/autoplay-floral-dance-05?sr=iiwedding", linkGambar: "https://i.ibb.co.com/DS2tLr3/56-Autoplay-Floral-Dance-05.png", keterangan: "" },
            { id: 57, nama: "Autoplay-Floral-Dance-06", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/autoplay-floral-dance-06?sr=iiwedding", linkGambar: "https://i.ibb.co.com/B2LSH5D6/57-Autoplay-Floral-Dance-06.png", keterangan: "" },
            { id: 58, nama: "Autoplay-Floral-Dance-07", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/autoplay-floral-dance-07?sr=iiwedding", linkGambar: "https://i.ibb.co.com/gbgV4kc9/58-Autoplay-Floral-Dance-07.png", keterangan: "" },
            { id: 59, nama: "Autoplay-Floral-Dance-08", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/autoplay-floral-dance-08?sr=iiwedding", linkGambar: "https://i.ibb.co.com/q3c0JJvZ/59-Autoplay-Floral-Dance-08.png", keterangan: "" },
            { id: 60, nama: "Autoplay-Floral-Dance-09", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/autoplay-floral-dance-09?sr=iiwedding", linkGambar: "https://i.ibb.co.com/rKrfrvZT/60-Autoplay-Floral-Dance-09.png", keterangan: "" },
            { id: 61, nama: "Full-Pattern-01", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/full-pattern-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/rRnBdJ7b/61-Full-Pattern-01.jpg", keterangan: "" },
            { id: 62, nama: "Full-Pattern-02", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/full-pattern-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/WmQKfMZ/62-Full-Pattern-02.jpg", keterangan: "" },
            { id: 63, nama: "Full-Pattern-03", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/full-pattern-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/vnfkWq2/63-Full-Pattern-03.jpg", keterangan: "" },
            { id: 64, nama: "Full-Pattern-Sfe-04", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/full-pattern-sfe-04?sr=iiwedding", linkGambar: "https://i.ibb.co.com/21Cj27Pq/64-Full-Pattern-04.jpg", keterangan: "" },
            { id: 65, nama: "Full-Pattern-Sfe-05", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/full-pattern-sfe-05?sr=iiwedding", linkGambar: "https://i.ibb.co.com/G31x8Zvx/65-Full-Pattern-05.jpg", keterangan: "" },
            { id: 66, nama: "Full-Pattern-Sfe-06", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/full-pattern-sfe-06?sr=iiwedding", linkGambar: "https://i.ibb.co.com/HT1FSZpt/66-Full-Pattern-06.jpg", keterangan: "" },
            { id: 67, nama: "Snowflakes-Effect-01", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/snowflakes-effect-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/S75Ng3hh/67-Snowflakes-Effect-01.jpg", keterangan: "" },
            { id: 68, nama: "Snowflakes-Effect-02", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/snowflakes-effect-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/993XDWhg/68-Snowflakes-Effect-02.jpg", keterangan: "" },
            { id: 69, nama: "Snowflakes-Effect-03", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/snowflakes-effect-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/twpVmGww/69-Snowflakes-Effect-03.jpg", keterangan: "" },
            { id: 70, nama: "Snowflakes-Effect-04", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/snowflakes-effect-04?sr=iiwedding", linkGambar: "https://i.ibb.co.com/ZR55BGvK/70-Snowflakes-Effect-04.jpg", keterangan: "" },
            { id: 71, nama: "Snowflakes-Effect-05", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/snowflakes-effect-05?sr=iiwedding", linkGambar: "https://i.ibb.co.com/RTQP93P5/71-Snowflakes-Effect-05.jpg", keterangan: "" },
            { id: 72, nama: "Snowflakes-Effect-06", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/snowflakes-effect-06?sr=iiwedding", linkGambar: "https://i.ibb.co.com/DPBSY7w8/72-Snowflakes-Effect-06.jpg", keterangan: "" },
            { id: 73, nama: "Snowflakes-Effect-07", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/snowflakes-effect-07?sr=iiwedding", linkGambar: "https://i.ibb.co.com/LhYJjQ8D/73-Snowflakes-Effect-07.jpg", keterangan: "" },
            { id: 74, nama: "Snowflakes-Effect-08", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/snowflakes-effect-08?sr=iiwedding", linkGambar: "https://i.ibb.co.com/b5KzcXxT/74-Snowflakes-Effect-08.jpg", keterangan: "" },
            { id: 75, nama: "Snowflakes-Effect-09", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/snowflakes-effect-09?sr=iiwedding", linkGambar: "https://i.ibb.co.com/LzyWS0Qf/75-Snowflakes-Effect-09.jpg", keterangan: "" },
            { id: 76, nama: "Snowflakes-Effect-10", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/snowflakes-effect-10?sr=iiwedding", linkGambar: "https://i.ibb.co.com/4ZTcHR3t/76-Snowflakes-Effect-10.jpg", keterangan: "" },
            { id: 77, nama: "Snowflakes-Effect-11", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/snowflakes-effect-11?sr=iiwedding", linkGambar: "https://i.ibb.co.com/xqPVvSXX/77-Snowflakes-Effect-11.jpg", keterangan: "" },
            { id: 78, nama: "Snowflakes-Effect-12", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/snowflakes-effect-12?sr=iiwedding", linkGambar: "https://i.ibb.co.com/C5YrQmMw/78-Snowflakes-Effect-12.jpg", keterangan: "" },
            { id: 79, nama: "Wide-01", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/wide-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/kVxRwgdg/79-Wide-01.jpg", keterangan: "" },
            { id: 80, nama: "Wide-02", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/wide-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/fzrtxBLP/80-Wide-02.jpg", keterangan: "" },
            { id: 81, nama: "Wide-03", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/wide-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/G3pRHKmR/81-Wide-03.jpg", keterangan: "" },
            { id: 82, nama: "Wide-04", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/wide-04?sr=iiwedding", linkGambar: "https://i.ibb.co.com/nNN1WNQb/82-Wide-04.jpg", keterangan: "" },
            { id: 83, nama: "Wide-05", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/wide-05?sr=iiwedding", linkGambar: "https://i.ibb.co.com/SDg6VTRB/83-Wide-05.jpg", keterangan: "" },
            { id: 84, nama: "Wide-06", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/wide-06?sr=iiwedding", linkGambar: "https://i.ibb.co.com/Q70DJnzY/84-Wide-06.jpg", keterangan: "" },
            { id: 85, nama: "Sm-01", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/sm-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/N6H2rvth/85-SM-01.jpg", keterangan: "" },
            { id: 86, nama: "Sm-02", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/sm-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/XwZCMyD/86-SM-02.jpg", keterangan: "" },
            { id: 87, nama: "Sm-03", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/sm-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/9kyR3gr0/87-SM-03.jpg", keterangan: "" },
            { id: 88, nama: "Sm-04", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/sm-04?sr=iiwedding", linkGambar: "https://i.ibb.co.com/GQTk0bwf/88-SM-04.jpg", keterangan: "" },
            { id: 89, nama: "Sm-05", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/sm-05?sr=iiwedding", linkGambar: "https://i.ibb.co.com/CpmgwV6h/89-SM-05.jpg", keterangan: "" },
            { id: 90, nama: "Sm-06", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/sm-06?sr=iiwedding", linkGambar: "https://i.ibb.co.com/4xjKBYd/90-SM-06.jpg", keterangan: "" },
            { id: 91, nama: "Sm-07", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/sm-07?sr=iiwedding", linkGambar: "https://i.ibb.co.com/8nvffsF4/91-SM-07.jpg", keterangan: "" },
            { id: 92, nama: "Sm-08", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/sm-08?sr=iiwedding", linkGambar: "https://i.ibb.co.com/YTwrqF9T/92-SM-08.jpg", keterangan: "" },
            { id: 93, nama: "Sm-09", kategori: "Alam", linkPreview: "https://app.smstory.id/pilihan-tema/sm-09?sr=iiwedding", linkGambar: "https://i.ibb.co.com/hxNzxQT0/93-SM-09.jpg", keterangan: "" },
            { id: 94, nama: "Card-01-Mv", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/card-01-mv?sr=iiwedding", linkGambar: "https://i.ibb.co.com/Gfd8QR8V/94-Card-01-MV.jpg", keterangan: "" },
            { id: 95, nama: "Card-02Mv", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/card-02-mv?sr=iiwedding", linkGambar: "https://i.ibb.co.com/BKf7fQwX/95-Card-02-MV.jpg", keterangan: "" },
            { id: 96, nama: "Card-03-Mv", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/card-03-mv?sr=iiwedding", linkGambar: "https://i.ibb.co.com/dwN3bnTH/96-Card-03-MV.jpg", keterangan: "" },
            { id: 97, nama: "Card-04-Mv-Full-Dark", kategori: "Dark", linkPreview: "https://app.smstory.id/pilihan-tema/card-04-mv-full-dark?sr=iiwedding", linkGambar: "https://i.ibb.co.com/4ZfZ3VxZ/97-Card-04-MV-Full-Dark.jpg", keterangan: "" },
            { id: 98, nama: "Card-05-Mv-Full-Dark", kategori: "Dark", linkPreview: "https://app.smstory.id/pilihan-tema/card-05-mv-full-dark?sr=iiwedding", linkGambar: "https://i.ibb.co.com/23HvcdSS/98-Card-05-MV-Full-Dark.jpg", keterangan: "" },
            { id: 99, nama: "Card-06-Mv-Full-Dark", kategori: "Dark", linkPreview: "https://app.smstory.id/pilihan-tema/card-06-mv-full-dark?sr=iiwedding", linkGambar: "https://i.ibb.co.com/zHmghKMW/99-Card-06-MV-Full-Dark.jpg", keterangan: "" },
            { id: 100, nama: "Boxed-01-Mv", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/boxed-01-mv?sr=iiwedding", linkGambar: "https://i.ibb.co.com/1tnNSgKj/100-Boxed-01-MV.jpg", keterangan: "" },
            { id: 101, nama: "Boxed-02-Mv", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/boxed-02-mv?sr=iiwedding", linkGambar: "https://i.ibb.co.com/S7V9y9KK/101-Boxed-02-MV.jpg", keterangan: "" },
            { id: 102, nama: "Boxed-03-Mv", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/boxed-03-mv?sr=iiwedding", linkGambar: "https://i.ibb.co.com/27kjKf2n/102-Boxed-03-MV.jpg", keterangan: "" },
            { id: 103, nama: "Boxed-04-Mv", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/boxed-04-mv?sr=iiwedding", linkGambar: "https://i.ibb.co.com/q398LjbD/103-Boxed-04-MV.jpg", keterangan: "" },
            { id: 104, nama: "Boxed-05-Mv", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/boxed-05-mv?sr=iiwedding", linkGambar: "https://i.ibb.co.com/23Cb4Sph/104-Boxed-05-MV.jpg", keterangan: "" },
            { id: 105, nama: "Boxed-06-Mv", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/boxed-06-mv?sr=iiwedding", linkGambar: "https://i.ibb.co.com/wZQT0pT6/105-Boxed-06-MV.jpg", keterangan: "" },
            { id: 106, nama: "Frame-01", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/frame-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/TqLY1VLQ/106-Frame-01.jpg", keterangan: "" },
            { id: 107, nama: "Frame-02", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/frame-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/zWcMcpN2/107-Frame-02.jpg", keterangan: "" },
            { id: 108, nama: "Frame-03", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/frame-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/dwVrQQP6/108-Frame-03.jpg", keterangan: "" },
            { id: 109, nama: "Frame-04", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/frame-04?sr=iiwedding", linkGambar: "https://i.ibb.co.com/GQ42Twcc/109-Frame-04.jpg", keterangan: "" },
            { id: 110, nama: "Frame-05", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/frame-05?sr=iiwedding", linkGambar: "https://i.ibb.co.com/xqRwsrBx/110-Frame-05.jpg", keterangan: "" },
            { id: 111, nama: "Frame-06", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/frame-06?sr=iiwedding", linkGambar: "https://i.ibb.co.com/1ffdnPsZ/111-Frame-06.jpg", keterangan: "" },
            { id: 112, nama: "Frame-07", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/frame-07?sr=iiwedding", linkGambar: "https://i.ibb.co.com/933j6Qd9/112-Frame-07.jpg", keterangan: "" },
            { id: 113, nama: "Frame-08", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/frame-08?sr=iiwedding", linkGambar: "https://i.ibb.co.com/KxrX7nkv/113-Frame-08.jpg", keterangan: "" },
            { id: 114, nama: "Frame-09", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/frame-09?sr=iiwedding", linkGambar: "https://i.ibb.co.com/SXjfqj5j/114-Frame-09.jpg", keterangan: "" },
            { id: 115, nama: "Simple-Corner-01", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/simple-corner-01?sr=iiwedding", linkGambar: "https://i.ibb.co.com/h1wHLHNB/115-Simple-Corner-01.jpg", keterangan: "" },
            { id: 116, nama: "Simple-Corner-02", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/simple-corner-02?sr=iiwedding", linkGambar: "https://i.ibb.co.com/5gR50grM/116-Simple-Corner-02.jpg", keterangan: "" },
            { id: 117, nama: "Simple-Corner-03", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/simple-corner-03?sr=iiwedding", linkGambar: "https://i.ibb.co.com/cSMzm1yc/117-Simple-Corner-03.jpg", keterangan: "" },
            { id: 118, nama: "Simple-Corner-04", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/simple-corner-04?sr=iiwedding", linkGambar: "https://i.ibb.co.com/0pjtnMzr/118-Simple-Corner-04.jpg", keterangan: "" },
            { id: 119, nama: "Simple-Corner-05", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/simple-corner-05?sr=iiwedding", linkGambar: "https://i.ibb.co.com/bgTxSjWG/119-Simple-Corner-05.jpg", keterangan: "" },
            { id: 120, nama: "Simple-Corner-06", kategori: "Bunga", linkPreview: "https://app.smstory.id/pilihan-tema/simple-corner-06?sr=iiwedding", linkGambar: "https://i.ibb.co.com/B2WYqSgS/120-Simple-Corner-06.jpg", keterangan: "" },
            { id: 121, nama: "Netflix", kategori: "Luxury", linkPreview: "https://invite.truelove.my.id/tema-netflix/", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/07/tema-netflix-thumb.jpg", keterangan: "Fast" },
            { id: 122, nama: "The Lux 1", kategori: "Luxury", linkPreview: "https://invite.truelove.my.id/tema-the-lux-1/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/05/lux1.webp", keterangan: "Fast" },
            { id: 123, nama: "The Lux 2", kategori: "Luxury", linkPreview: "https://invite.truelove.my.id/tema-lux-2/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/05/lux2.webp", keterangan: "Fast" },
            { id: 124, nama: "The Lux 3", kategori: "Luxury", linkPreview: "https://invite.truelove.my.id/tema-lux-3/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/05/lux3.webp", keterangan: "Fast" },
            { id: 125, nama: "The Lux 4", kategori: "Luxury", linkPreview: "https://invite.truelove.my.id/tema-lux-4/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/05/lux4.webp", keterangan: "Fast" },
            { id: 126, nama: "The Lux 5", kategori: "Luxury", linkPreview: "https://invite.truelove.my.id/tema-lux-5/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/05/lux5.webp", keterangan: "Fast" },
            { id: 127, nama: "The Lux 6", kategori: "Luxury", linkPreview: "https://invite.truelove.my.id/tema-lux-6/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/05/lux6.webp", keterangan: "Fast" },
            { id: 128, nama: "The Lux 7", kategori: "Luxury", linkPreview: "https://invite.truelove.my.id/tema-lux-7/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/05/lux7.webp", keterangan: "Fast" },
            { id: 129, nama: "The Lux 8", kategori: "Luxury", linkPreview: "https://invite.truelove.my.id/tema-lux-8/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/05/lux8.webp", keterangan: "Fast" },
            { id: 130, nama: "The Lux 9", kategori: "Luxury", linkPreview: "https://invite.truelove.my.id/tema-lux-9/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Lux-9-1.webp", keterangan: "Fast" },
            { id: 131, nama: "The Lux 10", kategori: "Luxury", linkPreview: "https://invite.truelove.my.id/temea-lux-10/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Lux10.webp", keterangan: "Fast" },
            { id: 132, nama: "Jawa 2", kategori: "Adat", linkPreview: "https://invite.truelove.my.id/adat-jawa-1/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/temajawa1.jpg", keterangan: "Fast" },
            { id: 133, nama: "Jawa 3", kategori: "Adat", linkPreview: "https://invite.truelove.my.id/adat-jawa-2/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/adat-jawa-2.jpg", keterangan: "Fast" },
            { id: 134, nama: "Jawa 4", kategori: "Adat", linkPreview: "https://invite.truelove.my.id/tema-jawa-3/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/ADAT-JAWA-3.jpg", keterangan: "Fast" },
            { id: 135, nama: "Sunda 2", kategori: "Adat", linkPreview: "https://invite.truelove.my.id/sunda-1/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/ADAT-SUNDA.jpg", keterangan: "Fast" },
            { id: 136, nama: "Batak 1", kategori: "Adat", linkPreview: "https://invite.truelove.my.id/tema-adat-batak-1/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/temabatak1.jpg", keterangan: "Fast" },
            { id: 137, nama: "Betawi 1", kategori: "Adat", linkPreview: "https://invite.truelove.my.id/betawi-1/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/betawi-1.jpg", keterangan: "Fast" },
            { id: 138, nama: "Dayak 1", kategori: "Adat", linkPreview: "https://invite.truelove.my.id/dayak-1/", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/temadayak1.jpg", keterangan: "Fast" },
            { id: 139, nama: "Minang 2", kategori: "Adat", linkPreview: "https://invite.truelove.my.id/minang-1/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/temaminang1.jpg", keterangan: "Fast" },
            { id: 140, nama: "Nias 1", kategori: "Adat", linkPreview: "https://invite.truelove.my.id/adat-nias-1/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/ADAT-NIAS.jpg", keterangan: "Fast" },
            { id: 141, nama: "Bali 1", kategori: "Adat", linkPreview: "https://invite.truelove.my.id/adat-bali-1/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/adat-Bali.jpg", keterangan: "Fast" },
            { id: 142, nama: "Japanese Sakura", kategori: "Adat", linkPreview: "https://invite.truelove.my.id/hanami-sakura/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/hanami-sakura.jpg", keterangan: "Fast" },
            { id: 143, nama: "Japanese Hanaui Sarang", kategori: "Adat", linkPreview: "https://invite.truelove.my.id/hanaui-sarang/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/hanuisarang.jpg", keterangan: "Fast" },
            { id: 144, nama: "Amethyst Dream", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/wedding-amethyst-dream/", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Midnight-04-Large.jpeg", keterangan: "Fast" },
            { id: 145, nama: "Crimson Romance", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/3d-crimson-romance/", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Midnight-03-Large.jpeg", keterangan: "Fast" },
            { id: 146, nama: "Crimson Tanpa Foto", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/crimson-tanpa-foto/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Midnight-03-Large.jpeg", keterangan: "Fast" },
            { id: 147, nama: "Emerald Romance", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/3d-emerald-romance/", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Midnight-05-Large.jpeg", keterangan: "Fast" },
            { id: 148, nama: "Midnight Garden", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/3d-midnight-garden/", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Midnight-01-Large.jpeg", keterangan: "Fast" },
            { id: 149, nama: "Motion Islamic 1", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/islamic-motion-1/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/09/Mockup-Elemenpress-Islamic-01-Large.jpeg", keterangan: "Fast" },
            { id: 150, nama: "Motion Islamic 2", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/islamic-motion-2/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/09/Mockup-Elemenpress-Islamic-02-Large.jpeg", keterangan: "Fast" },
            { id: 151, nama: "Motion Islamic 3", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/islamic-motion-3/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/09/Mockup-Elemenpress-Islamic-03-Large.jpeg", keterangan: "Fast" },
            { id: 152, nama: "Motion Islamic 4", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/islamic-motion-4/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/09/Mockup-Elemenpress-Islamic-04-Large.jpeg", keterangan: "Fast" },
            { id: 153, nama: "Motion Islamic 5", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/islamic-motion-5/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/09/Mockup-Elemenpress-Islamic-05-Large.jpeg", keterangan: "Fast" },
            { id: 154, nama: "Royal Twilight", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/3d-royal-twilight/", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Midnight-02-Large.jpeg", keterangan: "Fast" },
            { id: 155, nama: "3D Adat Bali", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/3d-adat-bali/", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/08/adatbali3d.jpg", keterangan: "Fast" },
            { id: 156, nama: "3D Adat Batak", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/3d-adat-batak", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/08/adatbatak3d.jpg", keterangan: "Fast" },
            { id: 157, nama: "3D Adat Betawi", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/3d-adat-betawi/", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/10/MOCKUP-Heritage-Vol-2-Betawi-Large.jpeg", keterangan: "Fast" },
            { id: 158, nama: "3D Adat Bugis", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/3d-adat-bugis-1/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/08/Adatbugis.jpg", keterangan: "Fast" },
            { id: 159, nama: "3D Adat Jawa", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/3d-motion-jawa-1/", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/07/thumb-3djawa.jpeg", keterangan: "Fast" },
            { id: 160, nama: "3D Adat Palembang", kategori: "3D Motion", linkPreview: "https://invite.truelove.my.id/3d-motion-adat-palembang/", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/09/MOCKUP-Heritage-Vol-2-Palembang-Large.jpeg", keterangan: "Fast" },
            { id: 161, nama: "Basic 1", kategori: "Basic", linkPreview: "https://invite.truelove.my.id/tema-bassic-1/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Bassic-1.jpg", keterangan: "Fast" },
            { id: 162, nama: "Basic 2", kategori: "Basic", linkPreview: "https://invite.truelove.my.id/tema-bassic-2/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Bassic-2.jpg", keterangan: "Fast" },
            { id: 163, nama: "Basic 3", kategori: "Basic", linkPreview: "https://invite.truelove.my.id/tema-bassic-3/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Bassic-3.jpg", keterangan: "Fast" },
            { id: 164, nama: "Basic 4", kategori: "Basic", linkPreview: "https://invite.truelove.my.id/tema-bassic-4/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Bassic-4.jpg", keterangan: "Fast" },
            { id: 165, nama: "Basic 5", kategori: "Basic", linkPreview: "https://invite.truelove.my.id/tema-bassic-5/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Bassic-5.jpg", keterangan: "Fast" },
            { id: 166, nama: "Basic 6", kategori: "Basic", linkPreview: "https://invite.truelove.my.id/tema-bassic-6/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Bassic-6.jpg", keterangan: "Fast" },
            { id: 167, nama: "Basic 7", kategori: "Basic", linkPreview: "https://invite.truelove.my.id/tema-bassic-7/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Bassic-7.jpg", keterangan: "Fast" },
            { id: 168, nama: "Basic 8", kategori: "Basic", linkPreview: "https://invite.truelove.my.id/tema-bassic-8/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Bassic-8.jpg", keterangan: "Fast" },
            { id: 169, nama: "Basic 9", kategori: "Basic", linkPreview: "https://invite.truelove.my.id/tema-bassic-9/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Bassic-9.jpg", keterangan: "Fast" },
            { id: 170, nama: "Basic 10", kategori: "Basic", linkPreview: "https://invite.truelove.my.id/tema-bassic-10/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Bassic-10.jpg", keterangan: "Fast" },
            { id: 171, nama: "Basic 11", kategori: "Basic", linkPreview: "https://invite.truelove.my.id/tema-bassic-11/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/bassic-11.jpg", keterangan: "Fast" },
            { id: 172, nama: "Basic 12", kategori: "Basic", linkPreview: "https://invite.truelove.my.id/tema-bassic-12/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/bassic-12.jpg", keterangan: "Fast" },
            { id: 173, nama: "Syar'i 1", kategori: "Islami", linkPreview: "https://invite.truelove.my.id/tema-syari-1/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Syari-1.jpg", keterangan: "Fast" },
            { id: 174, nama: "Syar'i 2", kategori: "Islami", linkPreview: "https://invite.truelove.my.id/tema-syari-2/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Syari-2.jpg", keterangan: "Fast" },
            { id: 175, nama: "Syar'i 3", kategori: "Islami", linkPreview: "https://invite.truelove.my.id/tema-syari-3/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Syari-3.jpg", keterangan: "Fast" },
            { id: 176, nama: "Syar'i 4", kategori: "Islami", linkPreview: "https://invite.truelove.my.id/tema-syari-4/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Syari-4.jpg", keterangan: "Fast" },
            { id: 177, nama: "Syar'i 5", kategori: "Islami", linkPreview: "https://invite.truelove.my.id/tema-syari-5/?to=Nama+Tamu", linkGambar: "https://invite.truelove.my.id/wp-content/uploads/2025/06/Syari-5.jpg", keterangan: "Fast" }
        ];

        // Get unique categories
        const categories = ['all', ...new Set(products.map(p => p.kategori))];

        // State
        let currentCategory = 'all';
        let currentSearch = '';

        // Initialize
        document.addEventListener('DOMContentLoaded', function() {
            renderFilters();
            renderProducts();
            setupEventListeners();
            updateCounts();
        });

        // Render filter buttons
        function renderFilters() {
            const filterContainer = document.getElementById('filterContainer');
            filterContainer.innerHTML = categories.map(category => `
                <button 
                    class="filter-btn px-6 py-2 rounded-full border-2 border-gray-300 hover:border-purple-500 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2 ${category === 'all' ? 'active' : ''}"
                    data-category="${category}"
                    onclick="filterByCategory('${category}')"
                >
                    ${category === 'all' ? 'Semua' : category}
                </button>
            `).join('');
        }

        // Setup event listeners
        function setupEventListeners() {
            // Search functionality
            const searchInput = document.getElementById('searchInput');
            searchInput.addEventListener('input', function(e) {
                currentSearch = e.target.value.toLowerCase();
                renderProducts();
                updateCounts();
            });

            // Add event listener for "all" button specifically
            const allButton = document.querySelector('[data-category="all"]');
            if (allButton) {
                allButton.addEventListener('click', function() {
                    console.log('All button clicked');
                    filterByCategory('all');
                });
            }
        }

        // Filter by category
        function filterByCategory(category) {
            console.log('Filter clicked:', category);
            currentCategory = category;
            
            // Update active state
            document.querySelectorAll('.filter-btn').forEach(btn => {
                btn.classList.remove('active');
            });
            document.querySelector(`[data-category="${category}"]`).classList.add('active');
            
            renderProducts();
            updateCounts();
        }

        // Render products
        function renderProducts() {
            const productGrid = document.getElementById('productGrid');
            const noResults = document.getElementById('noResults');
            
            let filteredProducts = products;
            
            // Filter by category
            if (currentCategory !== 'all') {
                filteredProducts = filteredProducts.filter(p => p.kategori === currentCategory);
            }
            
            // Filter by search
            if (currentSearch) {
                filteredProducts = filteredProducts.filter(p => 
                    p.nama.toLowerCase().includes(currentSearch) ||
                    p.kategori.toLowerCase().includes(currentSearch)
                );
            }
            
            if (filteredProducts.length === 0) {
                productGrid.innerHTML = '';
                noResults.classList.remove('hidden');
                return;
            }
            
            noResults.classList.add('hidden');
            
            productGrid.innerHTML = filteredProducts.map(product => `
                <div class="product-card bg-white rounded-lg shadow-md overflow-hidden cursor-pointer" onclick="window.open('${product.linkPreview}', '_blank')">
                    <div class="image-container aspect-[3/4] bg-gray-100">
                        <img 
                            src="${product.linkGambar}" 
                            alt="${product.nama}" 
                            class="w-full h-full object-cover"
                            onerror="this.style.display='none'; this.nextElementSibling.style.display='flex';"
                        >
                        <div class="hidden w-full h-full items-center justify-center bg-gray-200">
                            <svg class="w-12 h-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                            </svg>
                        </div>
                        ${product.keterangan ? `<span class="badge-fast">${product.keterangan}</span>` : ''}
                    </div>
                    <div class="p-4">
                        <h3 class="font-semibold text-gray-900 mb-2 text-sm truncate">${product.nama}</h3>
                        <span class="inline-block px-2 py-1 text-xs bg-purple-100 text-purple-800 rounded-full">
                            ${product.kategori}
                        </span>
                    </div>
                </div>
            `).join('');
        }

        // Update counts
        function updateCounts() {
            const productCount = document.getElementById('productCount');
            const totalProducts = document.getElementById('totalProducts');
            
            let filteredCount = products.length;
            
            if (currentCategory !== 'all') {
                filteredCount = products.filter(p => p.kategori === currentCategory).length;
            }
            
            if (currentSearch) {
                filteredCount = products.filter(p => 
                    p.nama.toLowerCase().includes(currentSearch) ||
                    p.kategori.toLowerCase().includes(currentSearch)
                ).length;
            }
            
            productCount.textContent = filteredCount;
            totalProducts.textContent = products.length;
        }
    </script>
</body>
</html>